pipeline {
    agent any

    tools {
        maven 'Maven 3.9.6' // Make sure this is configured in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/SalmaMohamedLotfy/Software-testing'
            }
        }

        stage('Run My Folder Tests') {
            steps {
                bat 'cd "Salma Mohamed Ahmed Lotfy_Total & Place Order in Cart Page Test Cases/Testing" && mvn test'
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
        }
    }
}
